name: Deploy to demonstration projects
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  dispatch:
    runs-on: ubuntu-latest
    environment: test environment
    name: actions-template-sync
    steps:
      - name: Generate token
        id: generate_token
        uses: wow-actions/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}

          # Optional.
          # github_api_url: https://api.example.com
          
          # Optional.
          # installation_id: 1337
          
          # Optional.
          # Using a YAML multiline string to avoid escaping the JSON quotes.
          # permissions: >-
          #   {"members": "read"}

          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token

          # Optional.
          # repository: owner/repo
      - name: Send request
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.bot_token }}" \
            https://api.github.com/repos/DavideMessinaARS/project-from-template/dispatches \
            -d '{"event_type":"deploy-to-dp","client_payload":{"unit":false,"integration":true}}'
