name: Deploy to demonstration projects
on: push
jobs:
  dispatch:
    runs-on: ubuntu-latest
    name: actions-template-sync
    steps:
      - run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/DavideMessinaARS/project-from-template/dispatches \
            -d '{"event_type":"deploy-to-dp","client_payload":{"unit":false,"integration":true}}'
