name: Deploy to demonstration projects
on:
  push:
    branches:
      - 'main'
jobs:
  dispatch:
    runs-on: ubuntu-latest
    environment: test environment
    name: actions-template-sync
    steps:
      - run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PWR_TOEKN }}" \
            https://api.github.com/repos/DavideMessinaARS/project-from-template/dispatches \
            -d '{"event_type":"deploy-to-dp","client_payload":{"unit":false,"integration":true}}'
